-- BATCH 3
/*Q1 — Customer Revenue
Find the total revenue generated by each customer.
Return:
•	customer_id 
•	customer_name 
•	total_revenue 
Sort by total revenue descending*/

select c.customer_id,c.customer_name,sum(o.amount) as total_revenue
from customers c inner join orders o 
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
order by total_revenue desc;

/*Q2 — Customer Order Frequency
Find the number of orders placed by each customer.
Return:
•	customer_id 
•	customer_name 
•	total_orders 
Include customers who have placed zero orders.
Sort by total_orders descending.*/

select c.customer_id,c.customer_name,count(o.customer_id) as total_orders
from customers c inner join orders o 
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
order by total_orders desc;

/*Q3 — Customer Average Order Value
For each customer, calculate their average order value.
Return:
•	customer_id 
•	customer_name 
•	average_order_value 
Include only customers who have placed at least one order.
Sort by average order value descending.*/

select c.customer_id,c.customer_name,sum(o.amount)/count(o.customer_id) as AOV
from customers c inner join orders o 
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
order by AOV desc;

/*Q4 — Customer Purchase Profile
For each customer, calculate:
•	customer_id 
•	customer_name 
•	total_orders 
•	total_revenue 
•	average_order_value 
Sort by total_revenue descending*/
select c.customer_id,c.customer_name,sum(o.amount) as total_revenue,count(o.customer_id) as total_orders,sum(o.amount)/count(o.customer_id) as AOV
from customers c inner join orders o 
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
order by total_revenue desc;

/*Q5 — High-Value Customers
Find customers whose total revenue is greater than 20,000.
Return:
•	customer_id 
•	customer_name 
•	total_revenue 
Sort by total revenue descending.
Business question: Which customers are generating significant revenue?*/

select c.customer_id,c.customer_name,sum(o.amount) as total_revenue
from customers c inner join orders o 
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
having total_revenue>20000
order by total_revenue desc;

/*Q6 — Product Revenue
Find the total revenue generated by each product.
Return:
•	product_id 
•	product_name 
•	category 
•	total_revenue 
Sort by total revenue descending.*/

select p.product_id,p.product_name,p.category,
sum(o.amount) as total_revenue
from products p inner join orders o 
on p.product_id=o.product_id
group by p.product_id,p.product_name,p.category
order by total_revenue desc;

/*Find how many orders each product has received.
Q7 — Product Order Volume
Return:
•	product_id 
•	product_name 
•	category 
•	total_orders 
Include products with zero orders.
Sort by total_orders descending.*/

select p.product_id,p.product_name,p.category,
count(o.product_id )as total_orders
from products p inner join orders o 
on p.product_id=o.product_id
group by p.product_id,p.product_name,p.category
order by total_orders desc;

/*Q8 — Category Performance
For each product category, calculate:
•	category 
•	total_orders 
•	total_revenue 
•	average_order_value 
Sort by total_revenue descending.
Business question: Which product categories contribute the most revenue?*/
select p.product_id,p.product_name,p.category,
count(o.product_id )as total_orders,
sum(o.amount) as total_revenue,
sum(o.amount)/count(o.product_id )as AOV
from products p inner join orders o 
on p.product_id=o.product_id
group by p.product_id,p.product_name,p.category
order by total_revenue desc;

/*Q9 — Best-Selling Product by Revenue
Find the product that generated the highest total revenue.
Return:
•	product_id 
•	product_name 
•	category 
•	total_revenue */
with prod_data as(
select p.product_id,p.product_name,p.category,
sum(o.amount) as total_revenue
from products p inner join orders o 
on p.product_id=o.product_id
group by p.product_id,p.product_name,p.category
)
select * from prod_data
where total_revenue=
(select max(total_revenue) from prod_data);

/*Q10 — Customer × Product Analysis
Find the total revenue generated by each customer-product combination.
Return:
•	customer_id 
•	customer_name 
•	product_id 
•	product_name 
•	total_orders 
•	total_revenue 
Sort by total_revenue descending.
Business question: Which customers are spending the most on which products?*/

with data as(
	select c.customer_id,c.customer_name,p.product_id, p.product_name,
    count(o.customer_id) as total_orders,
    sum(o.amount) as total_revenue
    from customers c inner join orders o 
    on c.customer_id=o.customer_id
    inner join products p 
    on p.product_id=o.product_id
group by
c.customer_id,c.customer_name,p.product_id, p.product_name
)
select* from data
order by customer_id,product_id;





